import type { Firma } from "./types";

// Beispiel-Betriebe, mit denen das Verzeichnis initial befüllt wird.
// In Produktion würden diese Einträge aus einer Datenbank kommen.
export const SEED_FIRMEN: Firma[] = [
  {
    id: "seed-001",
    firmenname: "Mahler Malerbetrieb GmbH",
    gewerk: "maler",
    ansprechpartner: "Stefan Mahler",
    telefon: "030 2244781",
    email: "kontakt@mahler-maler.de",
    plz: "10115",
    ort: "Berlin",
    betriebsgroesse: "6–20 Mitarbeiter",
    gesucht: ["Helfer", "Facharbeiter / Geselle"],
    kooperation: "zeitarbeit",
    dringlichkeit: "sofort",
    notiz: "Mehrere Großbaustellen im Frühjahr, brauchen kurzfristig Verstärkung.",
    erstelltAm: "2026-04-02T09:12:00.000Z",
  },
  {
    id: "seed-002",
    firmenname: "Holzwerk Brunner Schreinerei",
    gewerk: "schreiner",
    ansprechpartner: "Andrea Brunner",
    telefon: "089 556712",
    email: "info@holzwerk-brunner.de",
    plz: "80331",
    ort: "München",
    betriebsgroesse: "1–5 Mitarbeiter",
    gesucht: ["Facharbeiter / Geselle", "Azubi"],
    kooperation: "vermittlung",
    dringlichkeit: "kurzfristig",
    notiz: "Suchen erfahrenen Möbelschreiner zur Festanstellung.",
    erstelltAm: "2026-04-05T13:40:00.000Z",
  },
  {
    id: "seed-003",
    firmenname: "Nordbau Hoch- und Tiefbau GmbH",
    gewerk: "maurer",
    ansprechpartner: "Henning Petersen",
    telefon: "040 778120",
    email: "personal@nordbau.de",
    plz: "20095",
    ort: "Hamburg",
    betriebsgroesse: "21–50 Mitarbeiter",
    gesucht: ["Helfer", "Facharbeiter / Geselle", "Vorarbeiter"],
    kooperation: "beides",
    dringlichkeit: "sofort",
    notiz: "Dauerbedarf an Maurern und Bauhelfern, gerne auch ungelernt mit Erfahrung.",
    erstelltAm: "2026-04-06T08:05:00.000Z",
  },
  {
    id: "seed-004",
    firmenname: "Elektro Vogt & Söhne",
    gewerk: "elektro",
    ansprechpartner: "Markus Vogt",
    telefon: "0221 904455",
    email: "vogt@elektro-vogt.de",
    plz: "50667",
    ort: "Köln",
    betriebsgroesse: "6–20 Mitarbeiter",
    gesucht: ["Facharbeiter / Geselle", "Meister"],
    kooperation: "vermittlung",
    dringlichkeit: "kurzfristig",
    notiz: "Schwerpunkt Gebäudetechnik / Smart Home.",
    erstelltAm: "2026-04-08T10:22:00.000Z",
  },
  {
    id: "seed-005",
    firmenname: "Schneider Sanitär & Heizung",
    gewerk: "sanitaer",
    ansprechpartner: "Petra Schneider",
    telefon: "0711 332901",
    email: "buero@schneider-shk.de",
    plz: "70173",
    ort: "Stuttgart",
    betriebsgroesse: "6–20 Mitarbeiter",
    gesucht: ["Facharbeiter / Geselle", "Helfer"],
    kooperation: "zeitarbeit",
    dringlichkeit: "bedarf",
    notiz: "Saisonale Spitzen bei Heizungsmodernisierung.",
    erstelltAm: "2026-04-10T15:33:00.000Z",
  },
  {
    id: "seed-006",
    firmenname: "Dachprofi Wagner GmbH",
    gewerk: "dachdecker",
    ansprechpartner: "Thomas Wagner",
    telefon: "0911 447788",
    email: "info@dachprofi-wagner.de",
    plz: "90402",
    ort: "Nürnberg",
    betriebsgroesse: "6–20 Mitarbeiter",
    gesucht: ["Facharbeiter / Geselle", "Helfer"],
    kooperation: "beides",
    dringlichkeit: "saisonal",
    notiz: "Hauptsaison April–Oktober, dann hoher Personalbedarf.",
    erstelltAm: "2026-04-11T07:50:00.000Z",
  },
  {
    id: "seed-007",
    firmenname: "GerüstTeam Rhein-Main GmbH",
    gewerk: "geruestbau",
    ansprechpartner: "Ali Demir",
    telefon: "069 887234",
    email: "demir@geruestteam-rm.de",
    plz: "60311",
    ort: "Frankfurt am Main",
    betriebsgroesse: "21–50 Mitarbeiter",
    gesucht: ["Helfer", "Facharbeiter / Geselle", "Vorarbeiter"],
    kooperation: "zeitarbeit",
    dringlichkeit: "sofort",
    notiz: "Mehrere Projekte parallel, suchen laufend Gerüstbauer.",
    erstelltAm: "2026-04-12T11:18:00.000Z",
  },
  {
    id: "seed-008",
    firmenname: "Bodenwerk Krause",
    gewerk: "bodenleger",
    ansprechpartner: "Jens Krause",
    telefon: "0351 229014",
    email: "kontakt@bodenwerk-krause.de",
    plz: "01067",
    ort: "Dresden",
    betriebsgroesse: "1–5 Mitarbeiter",
    gesucht: ["Facharbeiter / Geselle"],
    kooperation: "vermittlung",
    dringlichkeit: "kurzfristig",
    notiz: "Parkett und Vinyl, suchen sauber arbeitenden Bodenleger.",
    erstelltAm: "2026-04-13T14:02:00.000Z",
  },
  {
    id: "seed-009",
    firmenname: "Trockenbau Lindner",
    gewerk: "trockenbau",
    ansprechpartner: "Robert Lindner",
    telefon: "0341 668523",
    email: "info@trockenbau-lindner.de",
    plz: "04109",
    ort: "Leipzig",
    betriebsgroesse: "6–20 Mitarbeiter",
    gesucht: ["Helfer", "Facharbeiter / Geselle"],
    kooperation: "zeitarbeit",
    dringlichkeit: "bedarf",
    notiz: "Innenausbau Bürogebäude, projektweiser Bedarf.",
    erstelltAm: "2026-04-15T09:44:00.000Z",
  },
  {
    id: "seed-010",
    firmenname: "Metallbau Hoffmann GmbH",
    gewerk: "metallbau",
    ansprechpartner: "Sabine Hoffmann",
    telefon: "0521 771260",
    email: "personal@metallbau-hoffmann.de",
    plz: "33602",
    ort: "Bielefeld",
    betriebsgroesse: "21–50 Mitarbeiter",
    gesucht: ["Facharbeiter / Geselle", "Vorarbeiter", "Meister"],
    kooperation: "beides",
    dringlichkeit: "kurzfristig",
    notiz: "Suchen Schweißer (MAG/WIG) mit Zertifikat.",
    erstelltAm: "2026-04-16T12:30:00.000Z",
  },
  {
    id: "seed-011",
    firmenname: "GrünRaum Garten- & Landschaftsbau",
    gewerk: "garten",
    ansprechpartner: "Lukas Becker",
    telefon: "0231 559087",
    email: "becker@gruenraum-galabau.de",
    plz: "44135",
    ort: "Dortmund",
    betriebsgroesse: "6–20 Mitarbeiter",
    gesucht: ["Helfer", "Facharbeiter / Geselle", "Azubi"],
    kooperation: "zeitarbeit",
    dringlichkeit: "saisonal",
    notiz: "Frühjahr bis Herbst hoher Bedarf an GaLaBau-Helfern.",
    erstelltAm: "2026-04-18T08:15:00.000Z",
  },
  {
    id: "seed-012",
    firmenname: "LogiCenter Logistik GmbH",
    gewerk: "logistik",
    ansprechpartner: "Nicole Wendt",
    telefon: "0203 668140",
    email: "recruiting@logicenter.de",
    plz: "47051",
    ort: "Duisburg",
    betriebsgroesse: "über 50 Mitarbeiter",
    gesucht: ["Helfer", "Facharbeiter / Geselle"],
    kooperation: "zeitarbeit",
    dringlichkeit: "sofort",
    notiz: "Laufender Bedarf: Staplerfahrer (Schein erforderlich) und Lagerhelfer.",
    erstelltAm: "2026-04-20T06:55:00.000Z",
  },
  {
    id: "seed-013",
    firmenname: "Zimmerei Holzmann",
    gewerk: "zimmerer",
    ansprechpartner: "Florian Holzmann",
    telefon: "0761 290338",
    email: "info@zimmerei-holzmann.de",
    plz: "79098",
    ort: "Freiburg im Breisgau",
    betriebsgroesse: "6–20 Mitarbeiter",
    gesucht: ["Facharbeiter / Geselle", "Vorarbeiter"],
    kooperation: "vermittlung",
    dringlichkeit: "kurzfristig",
    notiz: "Holzrahmenbau, suchen erfahrene Zimmerer.",
    erstelltAm: "2026-04-22T10:10:00.000Z",
  },
  {
    id: "seed-014",
    firmenname: "BlitzBlank Gebäudereinigung",
    gewerk: "reinigung",
    ansprechpartner: "Maria Schäfer",
    telefon: "0511 447029",
    email: "kontakt@blitzblank-hannover.de",
    plz: "30159",
    ort: "Hannover",
    betriebsgroesse: "über 50 Mitarbeiter",
    gesucht: ["Helfer"],
    kooperation: "zeitarbeit",
    dringlichkeit: "bedarf",
    notiz: "Unterhalts- und Bauschlussreinigung, flexible Einsätze.",
    erstelltAm: "2026-04-24T16:20:00.000Z",
  },
];
